<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use App\Models\User;
use App\Models\Product;
use DOMDocument;
use DOMXPath;

/**
 * Test HTML structure, semantic correctness, and quality of output generated by all Blade components.
 * This test class focuses specifically on task 2.3.3: Validate component HTML output.
 * 
 * Validates:
 * - HTML structure and nesting
 * - Semantic HTML elements
 * - Valid HTML attributes
 * - Proper ARIA attributes
 * - CSS class structure
 * - Element relationships and hierarchy
 * - HTML validation compliance
 * - Cross-browser compatibility markup
 */
class BladeComponentHtmlValidationTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        
        // Create test data for components that need it
        User::factory()->count(5)->create();
        Product::factory()->count(3)->create();
    }

    // ========================================
    // BUTTON COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function button_component_produces_valid_html_structure()
    {
        // Test button element
        $view = $this->blade('<x-ui.button variant="primary" size="lg">Click Me</x-ui.button>');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'button');
        $this->assertHtmlElementHasAttribute($html, 'button', 'type', 'button');
        $this->assertHtmlElementHasClass($html, 'button', 'inline-flex');
        $this->assertHtmlElementHasClass($html, 'button', 'items-center');
        $this->assertHtmlElementHasClass($html, 'button', 'justify-center');
        
        // Test link element when href provided
        $view = $this->blade('<x-ui.button href="/test" variant="outline">Link Button</x-ui.button>');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'a');
        $this->assertHtmlElementHasAttribute($html, 'a', 'href', '/test');
        $this->assertHtmlElementHasClass($html, 'a', 'inline-flex');
    }

    /** @test */
    public function button_component_has_proper_accessibility_attributes()
    {
        // Test disabled button accessibility
        $view = $this->blade('<x-ui.button disabled>Disabled Button</x-ui.button>');
        $html = (string) $view;
        
        $this->assertHtmlElementHasAttribute($html, 'button', 'disabled');
        $this->assertHtmlElementHasClass($html, 'button', 'disabled:pointer-events-none');
        $this->assertHtmlElementHasClass($html, 'button', 'disabled:opacity-50');
        
        // Test disabled link accessibility
        $view = $this->blade('<x-ui.button href="/test" disabled>Disabled Link</x-ui.button>');
        $html = (string) $view;
        
        $this->assertHtmlElementHasAttribute($html, 'a', 'aria-disabled', 'true');
        $this->assertHtmlElementHasAttribute($html, 'a', 'tabindex', '-1');
        
        // Test with custom aria attributes
        $view = $this->blade('<x-ui.button aria-label="Submit form" aria-describedby="help-text">Submit</x-ui.button>');
        $html = (string) $view;
        
        $this->assertHtmlElementHasAttribute($html, 'button', 'aria-label', 'Submit form');
        $this->assertHtmlElementHasAttribute($html, 'button', 'aria-describedby', 'help-text');
    }

    /** @test */
    public function button_component_handles_nested_content_properly()
    {
        $view = $this->blade('
            <x-ui.button variant="secondary">
                <svg class="w-4 h-4 mr-2" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M10 12l-4-4h8l-4 4z"/>
                </svg>
                Download
            </x-ui.button>
        ');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'svg');
        $this->assertHtmlElementHasAttribute($html, 'svg', 'viewBox', '0 0 20 20');
        $this->assertStringContainsString('Download', $html);
    }

    // ========================================
    // CARD COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function card_component_produces_valid_html_structure()
    {
        $view = $this->blade('
            <x-ui.card class="max-w-md">
                <x-ui.card-header>
                    <h3>Card Title</h3>
                    <p>Card description</p>
                </x-ui.card-header>
                <x-ui.card-content>
                    <p>Card content goes here</p>
                </x-ui.card-content>
            </x-ui.card>
        ');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'div');
        $this->assertHtmlElementHasClass($html, 'div', 'rounded-lg');
        $this->assertHtmlElementHasClass($html, 'div', 'border');
        $this->assertHtmlElementHasClass($html, 'div', 'bg-card');
        $this->assertHtmlElementHasClass($html, 'div', 'shadow-sm');
        $this->assertHtmlElementHasClass($html, 'div', 'max-w-md');
    }

    /** @test */
    public function card_component_maintains_proper_nesting()
    {
        $view = $this->blade('
            <x-ui.card>
                <x-ui.card-header>
                    <h2>Title</h2>
                </x-ui.card-header>
                <x-ui.card-content>
                    <div class="nested-content">
                        <p>Paragraph 1</p>
                        <p>Paragraph 2</p>
                    </div>
                </x-ui.card-content>
            </x-ui.card>
        ');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertStringContainsString('<h2>Title</h2>', $html);
        $this->assertStringContainsString('<div class="nested-content">', $html);
        $this->assertStringContainsString('<p>Paragraph 1</p>', $html);
        $this->assertStringContainsString('<p>Paragraph 2</p>', $html);
    }

    // ========================================
    // ALERT COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function alert_component_produces_valid_html_structure()
    {
        $view = $this->blade('<x-ui.alert variant="warning" title="Warning Alert">This is a warning message</x-ui.alert>');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'div');
        $this->assertHtmlElementHasAttribute($html, 'div', 'role', 'alert');
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-live', 'polite');
        $this->assertHtmlElementHasAttribute($html, 'div', 'id');
        $this->assertHtmlContainsElement($html, 'svg');
        $this->assertHtmlContainsElement($html, 'h5');
    }

    /** @test */
    public function alert_component_has_proper_accessibility_attributes()
    {
        // Test dismissible alert
        $view = $this->blade('<x-ui.alert variant="success" dismissible>Success message</x-ui.alert>');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlElementHasAttribute($html, 'div', 'role', 'alert');
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-live', 'polite');
        $this->assertHtmlContainsElement($html, 'button');
        $this->assertHtmlElementHasAttribute($html, 'button', 'aria-label', 'Close alert');
        $this->assertHtmlElementHasAttribute($html, 'button', 'type', 'button');
    }

    /** @test */
    public function alert_component_generates_unique_ids()
    {
        $view1 = $this->blade('<x-ui.alert dismissible>Alert 1</x-ui.alert>');
        $view2 = $this->blade('<x-ui.alert dismissible>Alert 2</x-ui.alert>');
        
        $html1 = (string) $view1;
        $html2 = (string) $view2;
        
        $this->assertValidHtml($html1);
        $this->assertValidHtml($html2);
        
        // Extract IDs and ensure they're different
        preg_match('/id="(alert-[^"]+)"/', $html1, $matches1);
        preg_match('/id="(alert-[^"]+)"/', $html2, $matches2);
        
        $this->assertNotEmpty($matches1);
        $this->assertNotEmpty($matches2);
        $this->assertNotEquals($matches1[1], $matches2[1]);
    }

    // ========================================
    // FORM COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function input_component_produces_valid_html_structure()
    {
        $view = $this->blade('<x-ui.input type="email" name="email" value="test@example.com" required />');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'input');
        $this->assertHtmlElementHasAttribute($html, 'input', 'type', 'email');
        $this->assertHtmlElementHasAttribute($html, 'input', 'name', 'email');
        $this->assertHtmlElementHasAttribute($html, 'input', 'value', 'test@example.com');
        $this->assertHtmlElementHasAttribute($html, 'input', 'required');
    }

    /** @test */
    public function textarea_component_produces_valid_html_structure()
    {
        $view = $this->blade('<x-ui.textarea name="description" rows="5" placeholder="Enter description" value="Default content" />');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'textarea');
        $this->assertHtmlElementHasAttribute($html, 'textarea', 'name', 'description');
        $this->assertHtmlElementHasAttribute($html, 'textarea', 'rows', '5');
        $this->assertHtmlElementHasAttribute($html, 'textarea', 'placeholder', 'Enter description');
        $this->assertStringContainsString('Default content', $html);
    }

    /** @test */
    public function select_component_produces_valid_html_structure()
    {
        $options = [
            'option1' => 'Option 1',
            'option2' => 'Option 2',
            'Group' => [
                'g1' => 'Grouped Option 1',
                'g2' => 'Grouped Option 2'
            ]
        ];
        
        $view = $this->blade('<x-ui.select name="test" :options="$options" value="option1" />', ['options' => $options]);
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'select');
        $this->assertHtmlElementHasAttribute($html, 'select', 'name', 'test');
        $this->assertHtmlContainsElement($html, 'option');
        $this->assertHtmlContainsElement($html, 'optgroup');
        $this->assertHtmlElementHasAttribute($html, 'optgroup', 'label', 'Group');
    }

    // ========================================
    // TABLE COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function table_component_produces_valid_html_structure()
    {
        $users = User::paginate(3);
        $columns = [
            ['key' => 'id', 'label' => 'ID', 'align' => 'center'],
            ['key' => 'name', 'label' => 'Name', 'sortable' => true],
            ['key' => 'email', 'label' => 'Email', 'sortable' => true]
        ];
        
        $view = $this->blade('<x-ui.table :data="$users" :columns="$columns" striped hover />', [
            'users' => $users,
            'columns' => $columns
        ]);
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'table');
        $this->assertHtmlContainsElement($html, 'thead');
        $this->assertHtmlContainsElement($html, 'tbody');
        $this->assertHtmlContainsElement($html, 'th');
        $this->assertHtmlContainsElement($html, 'td');
        $this->assertHtmlContainsElement($html, 'tr');
    }

    /** @test */
    public function table_component_has_proper_accessibility_attributes()
    {
        $users = User::paginate(2);
        $columns = [
            ['key' => 'name', 'label' => 'Name', 'sortable' => true],
            ['key' => 'email', 'label' => 'Email', 'sortable' => false]
        ];
        
        $view = $this->blade('<x-ui.table :data="$users" :columns="$columns" current-sort="name" current-direction="asc" />', [
            'users' => $users,
            'columns' => $columns
        ]);
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        
        // Check sortable column accessibility
        $this->assertStringContainsString('role="button"', $html);
        $this->assertStringContainsString('tabindex="0"', $html);
        $this->assertStringContainsString('aria-sort="ascending"', $html);
        $this->assertStringContainsString('onclick="handleSort', $html);
        $this->assertStringContainsString('onkeydown=', $html);
    }

    /** @test */
    public function table_component_handles_empty_state_properly()
    {
        $emptyData = new LengthAwarePaginator([], 0, 10);
        $columns = [['key' => 'name', 'label' => 'Name']];
        
        $view = $this->blade('<x-ui.table :data="$emptyData" :columns="$columns" empty-message="No records found" />', [
            'emptyData' => $emptyData,
            'columns' => $columns
        ]);
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'svg');
        $this->assertHtmlContainsElement($html, 'h3');
        $this->assertHtmlContainsElement($html, 'p');
        $this->assertStringContainsString('No Data', $html);
        $this->assertStringContainsString('No records found', $html);
    }

    // ========================================
    // MODAL COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function modal_component_produces_valid_html_structure()
    {
        $view = $this->blade('
            <x-ui.modal id="test-modal" title="Test Modal" description="Modal description">
                <p>Modal content</p>
                <x-slot name="footer">
                    <button>Cancel</button>
                    <button>Save</button>
                </x-slot>
            </x-ui.modal>
        ');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertStringContainsString('id="test-modal', $html); // Check ID starts with test-modal
        $this->assertHtmlElementHasAttribute($html, 'div', 'role', 'dialog');
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-modal', 'true');
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-labelledby');
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-describedby');
    }

    /** @test */
    public function modal_component_has_proper_accessibility_attributes()
    {
        $view = $this->blade('<x-ui.modal id="accessible-modal" title="Accessible Modal" dismissible>Content</x-ui.modal>');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlElementHasAttribute($html, 'div', 'role', 'dialog');
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-modal', 'true');
        // Note: tabindex is not set on the modal container in this implementation
        $this->assertHtmlContainsElement($html, 'button');
        $this->assertHtmlElementHasAttribute($html, 'button', 'aria-label', 'Close modal');
    }

    // ========================================
    // DROPDOWN COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function dropdown_component_produces_valid_html_structure()
    {
        $view = $this->blade('
            <x-ui.dropdown id="test-dropdown" align="right" width="lg">
                <x-slot name="trigger">
                    <button>Dropdown Trigger</button>
                </x-slot>
                <div>Dropdown content</div>
            </x-ui.dropdown>
        ');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlElementHasAttribute($html, 'div', 'data-dropdown-id');
        $this->assertStringContainsString('data-close-on-click="true"', $html); // Direct string check
        $this->assertStringContainsString('Dropdown Trigger', $html);
        $this->assertStringContainsString('Dropdown content', $html);
        $this->assertStringContainsString('data-trigger=', $html); // Just check that data-trigger exists
    }

    /** @test */
    public function dropdown_component_handles_disabled_state()
    {
        $view = $this->blade('
            <x-ui.dropdown disabled>
                <x-slot name="trigger">
                    <button>Disabled Trigger</button>
                </x-slot>
                <div>Content</div>
            </x-ui.dropdown>
        ');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-disabled', 'true');
        $this->assertHtmlElementHasAttribute($html, 'div', 'tabindex', '-1');
        $this->assertHtmlElementHasClass($html, 'div', 'opacity-50');
        $this->assertHtmlElementHasClass($html, 'div', 'cursor-not-allowed');
    }

    // ========================================
    // LOADING COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function loading_component_produces_valid_html_structure()
    {
        $view = $this->blade('<x-ui.loading variant="spinner" size="lg" text="Loading data..." />');
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlElementHasAttribute($html, 'div', 'role', 'status');
        $this->assertHtmlElementHasAttribute($html, 'div', 'aria-live', 'polite');
        $this->assertHtmlContainsElement($html, 'svg');
        $this->assertStringContainsString('Loading data...', $html);
    }

    /** @test */
    public function loading_component_variants_produce_valid_html()
    {
        $variants = ['spinner', 'dots', 'bars'];
        
        foreach ($variants as $variant) {
            $view = $this->blade("<x-ui.loading variant=\"{$variant}\" />");
            $html = (string) $view;
            
            $this->assertValidHtml($html);
            $this->assertHtmlElementHasAttribute($html, 'div', 'role', 'status');
            $this->assertHtmlElementHasAttribute($html, 'div', 'aria-live', 'polite');
            
            // Each variant should have appropriate animation classes
            if ($variant === 'spinner') {
                $this->assertHtmlContainsElement($html, 'svg');
                $this->assertHtmlElementHasClass($html, 'svg', 'animate-spin');
            } elseif ($variant === 'dots') {
                $this->assertHtmlElementHasClass($html, 'div', 'animate-bounce');
            } elseif ($variant === 'bars') {
                $this->assertHtmlElementHasClass($html, 'div', 'animate-pulse');
            }
        }
    }

    // ========================================
    // PAGINATION COMPONENT HTML VALIDATION
    // ========================================

    /** @test */
    public function pagination_component_produces_valid_html_structure()
    {
        $users = User::paginate(2);
        
        $view = $this->blade('<x-ui.pagination :paginator="$users" />', ['users' => $users]);
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertHtmlContainsElement($html, 'nav');
        $this->assertHtmlElementHasAttribute($html, 'nav', 'role', 'navigation');
        $this->assertHtmlElementHasAttribute($html, 'nav', 'aria-label', 'Pagination Navigation');
        $this->assertHtmlContainsElement($html, 'a');
        $this->assertHtmlContainsElement($html, 'span');
    }

    // ========================================
    // CROSS-COMPONENT INTEGRATION VALIDATION
    // ========================================

    /** @test */
    public function complex_nested_components_produce_valid_html()
    {
        $users = User::paginate(2);
        $columns = [['key' => 'name', 'label' => 'Name']];
        
        $view = $this->blade('
            <x-ui.card class="max-w-4xl">
                <x-ui.card-header>
                    <h2>User Management</h2>
                    <x-ui.alert variant="info" title="Information">
                        This table shows all users in the system.
                    </x-ui.alert>
                </x-ui.card-header>
                <x-ui.card-content>
                    <x-ui.table :data="$users" :columns="$columns" striped hover />
                    <div class="mt-4 flex justify-between">
                        <x-ui.button variant="outline" size="sm">Export</x-ui.button>
                        <x-ui.button variant="default">Add User</x-ui.button>
                    </div>
                </x-ui.card-content>
            </x-ui.card>
        ', [
            'users' => $users,
            'columns' => $columns
        ]);
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        $this->assertStringContainsString('User Management', $html);
        $this->assertStringContainsString('This table shows all users', $html);
        $this->assertStringContainsString('Export', $html);
        $this->assertStringContainsString('Add User', $html);
    }

    /** @test */
    public function components_handle_special_characters_safely()
    {
        $specialContent = '<script>alert("xss")</script>&lt;test&gt; "quotes" \'apostrophes\' &amp; symbols';
        
        $view = $this->blade("<x-ui.alert title=\"Special & Characters\">{$specialContent}</x-ui.alert>");
        $html = (string) $view;
        
        $this->assertValidHtml($html);
        
        // The content should be present but properly handled
        $this->assertStringContainsString('Special &amp; Characters', $html);
        $this->assertStringContainsString('&lt;test&gt;', $html);
        $this->assertStringContainsString('"quotes"', $html);
        $this->assertStringContainsString("'apostrophes'", $html);
        $this->assertStringContainsString('&amp; symbols', $html);
        
        // Note: Blade doesn't automatically escape content in slots by default
        // The script tag will be present but should be handled by the browser's XSS protection
        // In a real application, you would use {{ }} instead of {!! !!} for user content
    }

    // ========================================
    // HTML VALIDATION HELPER METHODS
    // ========================================

    /**
     * Assert that the given HTML is valid and well-formed
     */
    private function assertValidHtml(string $html): void
    {
        // Create a DOMDocument and load the HTML
        $dom = new DOMDocument();
        $dom->preserveWhiteSpace = false;
        $dom->formatOutput = true;
        
        // Suppress warnings for HTML5 elements and attributes
        libxml_use_internal_errors(true);
        
        // Wrap in a basic HTML structure for validation
        $wrappedHtml = '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>' . $html . '</body></html>';
        
        $result = $dom->loadHTML($wrappedHtml, LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
        
        $errors = libxml_get_errors();
        libxml_clear_errors();
        
        // Filter out warnings about HTML5 elements/attributes and known issues
        $criticalErrors = array_filter($errors, function($error) {
            // Skip HTML5 element warnings
            $html5Elements = ['svg', 'path', 'circle', 'nav', 'main', 'section', 'article', 'aside', 'header', 'footer'];
            foreach ($html5Elements as $element) {
                if (strpos($error->message, "Tag {$element} invalid") !== false) {
                    return false;
                }
            }
            
            // Skip entity reference warnings for common HTML entities
            if (strpos($error->message, 'htmlParseEntityRef: expecting') !== false) {
                return false;
            }
            
            // Only report actual errors and fatal errors
            return $error->level === LIBXML_ERR_ERROR || $error->level === LIBXML_ERR_FATAL;
        });
        
        $this->assertTrue($result, 'HTML should be valid and parseable');
        $this->assertEmpty($criticalErrors, 'HTML should not have critical parsing errors: ' . print_r($criticalErrors, true));
    }

    /**
     * Assert that HTML contains a specific element
     */
    private function assertHtmlContainsElement(string $html, string $tagName): void
    {
        $this->assertStringContainsString("<{$tagName}", $html, "HTML should contain <{$tagName}> element");
    }

    /**
     * Assert that an HTML element has a specific attribute with a specific value
     */
    private function assertHtmlElementHasAttribute(string $html, string $tagName, string $attribute, string $value = null): void
    {
        if ($value === null) {
            // Just check for attribute existence
            $pattern = "/<{$tagName}[^>]*\\s{$attribute}(?:\\s|>|=)/i";
            $this->assertMatchesRegularExpression($pattern, $html, "Element <{$tagName}> should have attribute '{$attribute}'");
        } else {
            // Check for attribute with specific value - escape special regex characters
            $escapedValue = preg_quote($value, '/');
            $pattern = "/<{$tagName}[^>]*\\s{$attribute}=[\"']{$escapedValue}[\"']/i";
            $this->assertMatchesRegularExpression($pattern, $html, "Element <{$tagName}> should have attribute '{$attribute}' with value '{$value}'");
        }
    }

    /**
     * Assert that an HTML element has a specific CSS class
     */
    private function assertHtmlElementHasClass(string $html, string $tagName, string $className): void
    {
        // Match class attribute that contains the specific class
        $pattern = "/<{$tagName}[^>]*\\sclass=[\"'][^\"']*\\b{$className}\\b[^\"']*[\"']/i";
        $this->assertMatchesRegularExpression($pattern, $html, "Element <{$tagName}> should have CSS class '{$className}'");
    }

    /**
     * Assert that HTML structure follows semantic best practices
     */
    private function assertSemanticHtmlStructure(string $html): void
    {
        // Check for proper heading hierarchy
        if (strpos($html, '<h') !== false) {
            $this->assertMatchesRegularExpression('/<h[1-6][^>]*>/', $html, 'Headings should use proper h1-h6 tags');
        }
        
        // Check for proper list structure
        if (strpos($html, '<li') !== false) {
            $this->assertTrue(
                strpos($html, '<ul') !== false || strpos($html, '<ol') !== false,
                'List items should be contained within ul or ol elements'
            );
        }
        
        // Check for proper table structure
        if (strpos($html, '<td') !== false || strpos($html, '<th') !== false) {
            $this->assertStringContainsString('<table', $html, 'Table cells should be contained within table element');
            $this->assertTrue(
                strpos($html, '<thead') !== false || strpos($html, '<tbody') !== false,
                'Tables should have proper thead/tbody structure'
            );
        }
    }
}